language: php

php:
  - 7.1

services:
  - mongodb

before_install:
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - pecl install -f mongodb-1.5.3

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
